import {
  pgTable,
  text,
  serial,
  integer,
  timestamp,
  pgEnum,
} from "drizzle-orm/pg-core";

export const keyStatusEnum = pgEnum("key_status", [
  "active",
  "redeemed",
  "invalid",
]);

export const consolePlatformEnum = pgEnum("console_platform", [
  "xbox",
  "playstation",
]);

// Keys generated by admins and redeemed by users for balance
export const keysTable = pgTable("bot_keys", {
  id: serial("id").primaryKey(),
  guildId: text("guild_id").notNull(),
  code: text("code").notNull().unique(),
  status: keyStatusEnum("status").notNull().default("active"),
  createdBy: text("created_by").notNull(),
  redeemedBy: text("redeemed_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  redeemedAt: timestamp("redeemed_at"),
});

// Per-user per-guild link balance
export const userBalancesTable = pgTable("bot_user_balances", {
  id: serial("id").primaryKey(),
  guildId: text("guild_id").notNull(),
  userId: text("user_id").notNull(),
  balance: integer("balance").notNull().default(0),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Per-guild configuration
export const guildConfigTable = pgTable("bot_guild_config", {
  guildId: text("guild_id").primaryKey(),
  linkChannelId: text("link_channel_id"),
  sellAuthApiKey: text("sellauth_api_key"),
  sellAuthProductId: text("sellauth_product_id"),
  xboxTutorialUrl: text("xbox_tutorial_url"),
  psnTutorialUrl: text("psn_tutorial_url"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Console accounts linked by users
export const consoleLinksTable = pgTable("bot_console_links", {
  id: serial("id").primaryKey(),
  guildId: text("guild_id").notNull(),
  userId: text("user_id").notNull(),
  platform: consolePlatformEnum("platform").notNull(),
  consoleUsername: text("console_username").notNull(),
  linkedAt: timestamp("linked_at").notNull().defaultNow(),
});

export type Key = typeof keysTable.$inferSelect;
export type UserBalance = typeof userBalancesTable.$inferSelect;
export type GuildConfig = typeof guildConfigTable.$inferSelect;
export type ConsoleLink = typeof consoleLinksTable.$inferSelect;
